# Use a imagem oficial do Nginx como base
FROM nginx:latest

# Copie o arquivo HTML para o diretório padrão do Nginx
COPY ./index.html /usr/share/nginx/html

# Exponha a porta 80 para permitir o acesso ao Nginx
EXPOSE 8080